name: build

on: [push, pull_request]

jobs:
  check:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test1
        run: ./test.sh

      - name: Test2
        run: export TEST=1 && ./test.sh

      - name: Test3
        run: ./test.sh
